CREATE TABLE EMPLOYEE(
empId INT PRIMARY KEY IDENTITY,
name VARCHAR(50) NOT NULL,
salary DECIMAL(10,2),
deptId INT REFERENCES  DEPARTMENT(deptId)
)

SELECT * FROM EMPLOYEE

CREATE TABLE DEPARTMENT(
deptId INT PRIMARY KEY IDENTITY,
name VARCHAR(50) NOT NULL,
)
SELECT * FROM DEPARTMENT 
--DROP TABLE EMPLOYEE
--DROP TABLE DEPARTMENT

SELECT name FROM EMPLOYEE WHERE deptId=2

SELECT * FROM EMPLOYEE WHERE deptId=2

Select name from DEPARTMENT where deptId=1
--Delete from DEPARTMENT where deptId=7